---
- name: Install Docker
  package:
    name: docker
    state: present

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Add ec2-user to Docker group
  user:
    name: ec2-user
    groups: docker
    append: true
