apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: ivolve
data:
  DB_HOST: mysql.ivolve.svc.cluster.local
  DB_USER: ivolve-user
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ivolve
type: Opaque
data:
  DB_PASSWORD: aXZvbHZlLXBhc3N3b3Jk
  MYSQL_ROOT_PASSWORD: cm9vdA==
