apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ivolve
type: Opaque
data:
  DB_PASSWORD: aXZvbHZlLXBhc3N3b3Jk     #ivolve-password
  MYSQL_ROOT_PASSWORD: cm9vdA==         #root