---
- name: Install Java
  package:
    name: java-17-amazon-corretto
    state: present

- name: Add Jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    state: present

- name: Install Jenkins
  package:
    name: jenkins
    state: present

- name: Start and enable Jenkins
  service:
    name: jenkins
    state: started
    enabled: true

- name: Wait for Jenkins to initialize
  wait_for:
    path: /var/lib/jenkins/secrets/initialAdminPassword
    timeout: 120

- name: Read and show Jenkins admin password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password
  changed_when: false

- name: Show Jenkins admin password
  debug:
    msg: "Jenkins admin password is: {{ jenkins_password.stdout }}"
